name: Unzip Project
on:
  push:
    paths:
      - 'api.zip'
  workflow_dispatch:
permissions:  
  contents: write  
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      # 删掉“Install unzip”这一步，直接执行解压
      - name: Unzip the package
        run: unzip api.zip -d ./api-files 
      - name: Commit unzipped files
        run: |
          git config --global user.name "Counsweeve"
          git config --global user.email "basya7@163.com"
          git add ./api-files
          git commit -m "Unzip api files" || echo "无新文件需要提交"
          git push
